runtime: python38

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT market_info.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
  DJANGO_SETTINGS_MODULE: "market_info.settings"
  REDIS_URL: 'market-info.appspot.com:6379'
  LOCAL_HOST: 'market-info.appspot.com'

runtime_config:
  python_version: 3
